# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 21:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0001_initial'),
    ]

    operations = [
    ]
