# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-10 23:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='username',
            field=models.CharField(blank=True, default=b'', max_length=100),
        ),
    ]
