# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 19:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentinfo',
            name='comment_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_parent', to='MoneyMonsterData.Comments'),
        ),
    ]
