# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-11 21:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0002_auto_20160405_1929'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='thumbnail',
            field=models.CharField(default='McFinn_I_Can_Build_It', max_length=255),
            preserve_default=False,
        ),
    ]
