# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-05 04:38
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0002_auto_20160405_0206'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='parent_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_parent', to='MoneyMonsterData.Video'),
        ),
    ]
