# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 21:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0002_auto_20160617_2109'),
    ]

    operations = [
     	migrations.RenameField('Comment', 'owner', 'user'),
    ]
