# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-03-17 00:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0004_auto_20160316_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlikes',
            name='liked',
            field=models.BooleanField(default=False),
        ),
    ]
