# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-04-25 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0004_auto_20160411_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizquestions',
            name='answer_four',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='answer_one',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='answer_three',
        ),
        migrations.RemoveField(
            model_name='quizquestions',
            name='answer_two',
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='answer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='quizquestions',
            name='false_answer',
            field=models.TextField(default='This is why its the answer', max_length=1000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='quizquestions',
            name='correct_answer',
            field=models.TextField(max_length=1000),
        ),
    ]
