# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-05-02 23:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0007_auto_20160425_2147'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Haps',
            new_name='Profile',
        ),
    ]
