# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0008_auto_20160502_2323'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='android',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='ios',
            new_name='hlsUrl',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnailUrl',
            new_name='thumbnailFilename',
        ),
        migrations.AddField(
            model_name='video',
            name='rtmpServerUrl',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='video',
            name='rtmpStreamName',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
