# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-16 17:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0009_auto_20160516_1730'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='hlsUrl',
            new_name='hls_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='rtmpServerUrl',
            new_name='rtmp_server_url',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='rtmpStreamName',
            new_name='rtmp_stream_name',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='thumbnailFilename',
            new_name='thumbnail_filename',
        ),
    ]
