# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-01 23:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('MoneyMonsterData', '0010_auto_20160516_1746'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quizanswers',
            name='quiz_question_id',
        ),
        migrations.RemoveField(
            model_name='quizanswers',
            name='user_id',
        ),
        migrations.AddField(
            model_name='quizresults',
            name='passed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='quizzes',
            name='video_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video', to='MoneyMonsterData.Video'),
        ),
        migrations.DeleteModel(
            name='QuizAnswers',
        ),
    ]
